<!DOCTYPE html>
<html lang="en">
<head>
  	<title><?=$page['page']='PIN Generate';?> | <?=$this->siteInfo['name'];?></title>
  	<?php $this->load->view('include/header'); ?>
</head>
<body>
  <!--===========top nav start=======-->
    	<?php $this->load->view('include/topbar'); ?>
  <!--===========top nav end===========-->
  	<div class="wrapper" id="wrapper">
    	<div class="left-container" id="left-container">
      	<!--========== Sidebar Start =============-->
      		<?php $this->load->view('include/sidebar',$page); ?>
      	<!--========== Sidebar End ===============-->
    	</div>
	    <div class="right-container" id="right-container">
	      	<div class="container-fluid">
		        <?php $this->load->view('include/page-top',$page); ?>
		        <!--//===============Main Container Start=============//-->
		        <div class="row padding-top">
		            <div class="col-xs-6 col-xs-offset-3">
						<div class="panel panel-info">
							<div class="panel-heading">
								<h3 class="panel-title">Send PIN (Direct User)</h3>
							</div>
							<div class="panel-body">
							  <?=form_open('auth/sendPinDirectUser');?>
								<div class="form-group">
									<label>User ID</label>
									<input type="text" onchange="return checkUser(this.value)" name="user_id" placeholder="Receiver's User ID" id="user_id" class="form-control txtupper" required>
								</div>
								<div class="form-group">
									<label>User Name</label>
									<input type="text" value="" class="form-control" placeholder="Enter User Id To Verify" readonly="" id="result">
								</div>
								
								  <div class="form-group">
									<label>Package Pin</label>
									<select name="product_id" class="form-control" required>
									<option value="">Please Select Product Pin</option>
								<?php $product = $this->db->get_where('base_plan')->result_array(); ?>
				        	<?php foreach ($product as $key => $value) { ?>
				        		<option value="<?=$value['id'];?>"><?=$value['name'];?></option>
				        	<?php } ?>
									</select>
								</div>
								<div class="form-group">
									<label>Number of PINs</label>
									<input type="text" value="1" name="quantity" placeholder="Paste PIN Here" id="direct" class="form-control" required>
								</div>
								<div class="form-group">
									<center><button id="sub" onclick="return confirm('Are you sure to transfer PIN');" class="btn btn-success">Send PIN <i class="fa fa-location-arrow"></i></button></center>
								</div>
							  </form>
							</div>
						</div>
					</div>        
		        </div>
		        <div class="row">
					<div class="col-lg-12">
						<div class="panel panel-success">
							<div class="panel-heading">
								<h3 class="panel-title">Generated PIN Status</h3>
							</div>
							<div class="panel-body">
								<table id="table2" class="table table-condensed table-bordered table-striped table-hover">
									<thead>
										<tr>
											<th>Sl No</th>
											<th>PIN</th>
											<th>Package</th>
											<th>User ID</th>
											<th>Date</th>
											<th>Generated By</th>
											<th>Status</th>
											<th>Activate Account</th>
										</tr>
									</thead>
									<tbody>
									<?php $res=$this->dbm->globalSelect('pin',['generate_by'=>'admin']); $i=1;
									if($res){
									foreach ($res as $key => $value) { ?>
										<tr>
											<td><?=$i;?></td>
											<td><?=$value['pin'];?></td>
											<td>
											    <?php $pak = $this->db->get_where('base_plan',['id'=>$value['product_id']])->row_array(); ?>
											    <?=$pak['name']; ?>
											</td>
											<td><?=$value['user_id'];?></td>
											<td><?=$this->dbm->dateFormat($value['gen_date']);?> <?=$value['gen_time'];?></td>
											<td><?=ucfirst($value['generate_by']);
												if($value['generate_by']=='admin'){ ?>
													<a onclick="return condelPin()" class="btn btn-sm btn-danger btn-xs btn-circle txtright" href="<?=base_url('auth/deletePin/'.$value['id'].'/'.$value['pin']);?>"><i class="fa fa-trash"></i></a>
												<?php } ?>
											</td>
											<td><?=($value['status']==1)?"<button class='btn btn-xs btn-success'>Active</button>":"<button class='btn btn-xs btn-danger'>Deactive</button>";?></td>
											<td><?php if($value['status']==1){
												echo $value['activated_account'];
											}else{ ?>
												<a href="#" onclick="return pinTopup('<?=$value['pin'];?>')" class="btn btn-sm btn-info">Topup Pin</a>
											<?php } ?>
										</td>
										</tr>
									<?php $i++; } } else{ ?>
										
									<?php } ?>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
	        <!--//===============Main Container End=============//-->
	      	</div>
	    </div>
  	</div>
  <!--==========Footer Start=============-->
  <?php $this->load->view('include/footer'); ?>
  <!--==========Footer End=============-->   
</body>
</html>


<!-- Bootstrap Modal fo Pin Topup -->
          <div class="modal fade" id="topUpModal" role="dialog">
            <div class="modal-dialog modal-sm">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal"><span class="glyphicon glyphicon-remove" style="color: red;"></span></button>
                  <h4 class="modal-title">Enter User ID</h4>
                </div>
                <div class="modal-body">
                  <div class="jumbotron">
                    <?=form_open('auth/activePinViaTopup'); ?>
                    <div class="input-group form-group">
                      <span class="input-group-btn">
                        <button class="btn btn-secondry" type="button">PIN</button>
                      </span>
                <input type="text" id="topupPin" name="pin" class="form-control" readonly>
              </div>
                    <div class="input-group form-group">
                <input type="text" id="userID" name="user_id" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                  <button id="verify" class="btn btn-warning" type="button">Verify!</button>
                </span>
              </div>
              <div class="input-group form-group">
                <p class="txtblue text-center" id="topupPinMsg"></p>
              </div>
                  </div>
                </div>
                <div class="modal-footer">

                </div>
                </form>
              </div>
            </div>
          </div>
        <!-- Modal End -->
<?php $this->load->view('include/loader'); ?>
<script type="text/javascript">
	$('.loader').hide();
	function checkUser(uid)
	{
		$('.loader').show();
		//$("#overlay").css('display','block');
		var uid=uid.toUpperCase();
		$.ajax({
			url:"<?=base_url('auth/getName');?>",
			data:{user_id:uid},
			type:'post',
			success:function(data)
			{
				if(data==0)
				{
					$('#result').val("User Not Found");
					$('#sub').attr('disabled',true);
				}else
				{
					$('#result').val(data);
					$('#sub').attr('disabled',false);
				}
				$('.loader').fadeOut();
				//$("#overlay").fadeOut().css('display','none');
			}
		});
	}
function sendPin(req_id,user_id,numPin)
{
	$('#req_id').val(req_id);
	$('#user_idRequest').val(user_id);
	$('#numPin').val(numPin);
	$('#noticeModal').modal('show');
}
$(document).ready(function() {
$('#table1').DataTable();
} );
$(document).ready(function() {
$('#table2').DataTable();
});

function chkUser(){
	var id=$('#user_idRequest').val();
	var req_id=$('#req_id').val();
	if(req_id=='')
	{
		$('#errReqId').html('Request ID is Required');
		return false;
	}
	if(id=='')
	{
		$('#errReUid').html('User ID is Required');
		return false;
	}
}

function condelPin()
	{
		var cnf =confirm('Are you Sure to Delete this PIN');
		if(cnf)
		{
			return true;
		}else
		{
			return false;
		}
	}
	function pinTopup(pin){
    $('#topupPin').val(pin);
    $('#topupPinMsg').html('');
    $('#topUpModal').modal('show');
  }
$('#verify').click(function()
  {
  	$('.loader').show();
    var uid=$('#userID').val();
      $.ajax({
        url:"<?=base_url('user/checkUserForpinTopup');?>",
        data:{user_id:uid},
        type:'post',
        success:function(data)
        {
          $('#topupPinMsg').html(data);
          $('.loader').fadeOut();
        }
      });
  });

</script>
<style type="text/css">
	.btn-circle{
		float:right;
	}
</style>